services:
  # Laravel PHP-FPM
  laravel-php-nginx-tcp:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
      target: php-base
    container_name: laravel-php-nginx-tcp
    restart: unless-stopped
    working_dir: /var/www/laravel
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_START: ${XDEBUG_START}
      XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
    networks:
      - laravel-nginx-tcp-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 | grep -q 'pong'"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Веб-сервер Nginx
  laravel-nginx-tcp:
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    container_name: laravel-nginx-tcp
    restart: unless-stopped
    networks:
      - laravel-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      laravel-php-nginx-tcp:
        condition: service_healthy

  # PostgreSQL (base: и для dev, и для prod)
  laravel-postgres-nginx-tcp:
    image: postgres:18.2-alpine
    container_name: laravel-postgres-nginx-tcp
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - laravel-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Redis (base: и для dev, и для prod)
  laravel-redis-nginx-tcp:
    image: redis:8.6-alpine
    container_name: laravel-redis-nginx-tcp
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    networks:
      - laravel-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
  redis-data:

networks:
  laravel-nginx-tcp-network:
    driver: bridge